In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
df = pd.read_csv("crsp_small_sample.csv")

df.head()

,date,AA,ABM,ABT,ADI,ADM,ADX,AEE,AEG,AEM,...,XLI,XLK,XLP,XLU,XLV,XLY,XOM,XRX,YUM,ZTR
0,2011-01-03,0.026641,0.019392,-0.001879,0.007433,0.010638,0.011173,0.002128,0.013051,-0.043546,...,0.007169,0.011115,0.001365,0.004866,0.009127,0.011762,0.019557,0.016493,0.000816,0.000000
1,2011-01-04,0.045570,-0.022007,0.009410,-0.011331,-0.000658,0.000921,0.007434,0.008052,-0.018948,...,-0.001424,0.003926,-0.002726,0.004525,0.003225,-0.005548,0.004695,-0.026473,-0.015278,0.000843
2,2011-01-05,0.002421,0.016104,0.000000,0.002132,0.004608,0.002760,-0.002108,0.014377,-0.005141,...,0.005133,0.005866,0.000342,-0.006164,0.002195,0.008236,-0.002670,0.005263,0.004758,-0.008499
3,2011-01-06,-0.012077,-0.011321,-0.002072,0.005585,0.038336,0.000917,-0.003873,-0.009449,-0.025698,...,-0.001702,0.005832,-0.003415,0.000954,0.004068,-0.006061,0.006426,0.000000,0.007000,0.002857
4,2011-01-07,0.003667,-0.015649,0.004152,-0.005819,0.008204,-0.003666,0.000000,0.007949,0.009604,...,0.001989,-0.004639,-0.005055,0.003575,-0.000623,-0.000530,0.005454,-0.013962,0.012472,-0.002849

In [3]:
df.shape

(2870, 696)

In [4]:
tot = df.shape[1]
num_assets = df.shape[1] // 5

int_choices = np.random.choice(range(0, tot), num_assets, replace=False)

len(int_choices) == num_assets

True

In [5]:
colnames = [df.columns[i] for i in int_choices]
df[["date"] + colnames].head()

,date,WHR,EBF,MUH,UDR,RRC,BBY,HCN,TDW,RMD,...,SEE,ING,SWK,KFY,PNM,SLG,NAD,PMM,MLI,DDS
0,2011-01-03,0.018462,0.019298,-0.000732,0.014881,0.014229,0.005249,0.016583,-0.006501,0.010970,...,0.012181,0.011236,0.017945,0.015145,0.016129,0.024145,-0.003876,-0.004341,0.007951,0.023458
1,2011-01-04,-0.014369,-0.017785,-0.005128,-0.031420,-0.017975,0.016826,-0.014041,-0.012900,0.007424,...,-0.007764,0.008081,-0.003820,-0.012788,0.011338,-0.012728,-0.001556,-0.001454,-0.018507,-0.029616
2,2011-01-05,0.006729,0.015771,-0.006303,-0.008651,-0.000670,0.018545,0.001885,0.021402,-0.020125,...,0.001956,-0.003006,-0.008111,0.000000,-0.010463,-0.002784,-0.001559,0.004367,0.008964,0.011943
3,2011-01-06,-0.021277,-0.016964,-0.002401,-0.007417,-0.000670,-0.012605,-0.002926,-0.019284,-0.002314,...,0.008590,-0.012060,-0.010853,-0.018998,-0.003776,-0.008667,-0.000781,-0.008696,-0.017770,0.039339
4,2011-01-07,-0.004211,-0.008855,0.002080,-0.008352,0.025257,0.003404,-0.006289,0.038192,-0.022035,...,0.003871,-0.020346,-0.015482,-0.018926,0.001516,-0.006372,0.001562,-0.001462,-0.015284,0.001766

In [6]:
new_df = df[["date"] + colnames]
new_df.set_index("date", inplace=True)

new_df.head()

,WHR,EBF,MUH,UDR,RRC,BBY,HCN,TDW,RMD,KMB,...,SEE,ING,SWK,KFY,PNM,SLG,NAD,PMM,MLI,DDS
date,,,,,,,,,,,,,,,,,,,,,
2011-01-03,0.018462,0.019298,-0.000732,0.014881,0.014229,0.005249,0.016583,-0.006501,0.010970,-0.006504,...,0.012181,0.011236,0.017945,0.015145,0.016129,0.024145,-0.003876,-0.004341,0.007951,0.023458
2011-01-04,-0.014369,-0.017785,-0.005128,-0.031420,-0.017975,0.016826,-0.014041,-0.012900,0.007424,0.004311,...,-0.007764,0.008081,-0.003820,-0.012788,0.011338,-0.012728,-0.001556,-0.001454,-0.018507,-0.029616
2011-01-05,0.006729,0.015771,-0.006303,-0.008651,-0.000670,0.018545,0.001885,0.021402,-0.020125,0.003339,...,0.001956,-0.003006,-0.008111,0.000000,-0.010463,-0.002784,-0.001559,0.004367,0.008964,0.011943
2011-01-06,-0.021277,-0.016964,-0.002401,-0.007417,-0.000670,-0.012605,-0.002926,-0.019284,-0.002314,-0.001426,...,0.008590,-0.012060,-0.010853,-0.018998,-0.003776,-0.008667,-0.000781,-0.008696,-0.017770,0.039339
2011-01-07,-0.004211,-0.008855,0.002080,-0.008352,0.025257,0.003404,-0.006289,0.038192,-0.022035,-0.000476,...,0.003871,-0.020346,-0.015482,-0.018926,0.001516,-0.006372,0.001562,-0.001462,-0.015284,0.001766

In [8]:
new_df.to_csv(os.path.join(os.getcwd(), "crsp_small_sample.csv"))

In [9]:
new_df = pd.read_csv("crsp_small_sample.csv")

new_df.head()

,date,WHR,EBF,MUH,UDR,RRC,BBY,HCN,TDW,RMD,...,SEE,ING,SWK,KFY,PNM,SLG,NAD,PMM,MLI,DDS
0,2011-01-03,0.018462,0.019298,-0.000732,0.014881,0.014229,0.005249,0.016583,-0.006501,0.010970,...,0.012181,0.011236,0.017945,0.015145,0.016129,0.024145,-0.003876,-0.004341,0.007951,0.023458
1,2011-01-04,-0.014369,-0.017785,-0.005128,-0.031420,-0.017975,0.016826,-0.014041,-0.012900,0.007424,...,-0.007764,0.008081,-0.003820,-0.012788,0.011338,-0.012728,-0.001556,-0.001454,-0.018507,-0.029616
2,2011-01-05,0.006729,0.015771,-0.006303,-0.008651,-0.000670,0.018545,0.001885,0.021402,-0.020125,...,0.001956,-0.003006,-0.008111,0.000000,-0.010463,-0.002784,-0.001559,0.004367,0.008964,0.011943
3,2011-01-06,-0.021277,-0.016964,-0.002401,-0.007417,-0.000670,-0.012605,-0.002926,-0.019284,-0.002314,...,0.008590,-0.012060,-0.010853,-0.018998,-0.003776,-0.008667,-0.000781,-0.008696,-0.017770,0.039339
4,2011-01-07,-0.004211,-0.008855,0.002080,-0.008352,0.025257,0.003404,-0.006289,0.038192,-0.022035,...,0.003871,-0.020346,-0.015482,-0.018926,0.001516,-0.006372,0.001562,-0.001462,-0.015284,0.001766